### ISSUE TITLE
Rebinding chat command doesn't appear to work

### ISSUE THREAD

**Issue by ChaosAlpha** [AntimoniumGame/Antimonium#93]
Tried to launch the key rebind GUI by using the chat command, but didn't seem to open.

**Comment by ElArGee** [comment]
Do you mean you tried typing the verb for rebinding keys into the chat input box?

**Comment by ChaosAlpha** [comment]
Nope, the "/keybind" chat command. There might have been an issue with new players permissions not setting up correctly on the little test server @Zuhayr booted up yesterday :D
I'll try at a later time this day with a local copy of my own to check it.
